/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semana7;

/**
 *
 * @author Gabriel
 */
import javax.swing.JButton;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import java.util.Collections;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.Timer;
public class JuegoMemorama extends javax.swing.JFrame {
    
    private JButton[][] botones=new JButton[6][6];
    private JButton boton1 = null;
    private JButton boton2 = null;
    
    private int numIntentos = 0;
    
    private JLabel labelIntentos = new JLabel("Intentos: 0");
    /**
     * Creates new form JuegoMemorama
     */
    public JuegoMemorama() {
        initComponents();
        
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 650));
        setSize(700,750);
        
        jPanel1.add(labelIntentos);
        
        ImageIcon hiddenOriginal = new ImageIcon("/Users/School/Desktop/imagenesMemorama/hidden.jpg");
        Image hiddenTamañoCustom = hiddenOriginal.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon hiddenIcon = new ImageIcon(hiddenTamañoCustom);
        
        for (int fila = 0; fila < 6; fila++) {
            for (int columna = 0; columna < 6; columna++) {
                botones[fila][columna] = new JButton();

                // Icono para que parezca carta oculta 
                botones[fila][columna].setIcon(hiddenIcon);
                botones[fila][columna].setEnabled(true);

                // Botón al panel que tiene GridLayout
                jPanel1.add(botones[fila][columna]);
            }
        }
        
        
        
        String[] nombreImg = {"joker.png", "ryuji.webp", "morgana.png", "ann.png", "yusuke.webp", "makoto.webp", "futaba.webp", "haru.webp", "akechi.webp", "blackMask.webp", "sojiro.webp", "maruki.webp", "kamoshida.webp", "shido.webp", "sae.webp", "kasumi.png", "shinya.webp", "igor.webp"};
        
        ArrayList<ImageIcon> imagenes = new ArrayList<>();
    
        String location = "/Users/School/Desktop/imagenesMemorama/";

        for (String nombre: nombreImg) {
            ImageIcon original = new ImageIcon(location + nombre);
            Image tamañoCustom = original.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon iconTamañoCustom = new ImageIcon(tamañoCustom);
            
            imagenes.add(iconTamañoCustom);
            imagenes.add(iconTamañoCustom);
        }

        Collections.shuffle(imagenes); 
        
        
        int index = 0;

        for (int fila = 0; fila < 6; fila++) {
            for (int columna = 0; columna < 6; columna++) {
               
                botones[fila][columna].setDisabledIcon(imagenes.get(index));
                index++;
                
                botones[fila][columna].addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        JButton boton = (JButton) e.getSource();

                        boton.setEnabled(false);
                    }
                });
                
                jPanel1.add(botones[fila][columna]);
            }
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoMemorama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
